version: '3.4'

services:
  openhab:
    restart: always
    volumes:
      - ./volumes/openhab/addons:/openhab/addons
      - ./volumes/openhab/conf:/openhab/conf
      - ./volumes/openhab/userdata:/openhab/userdata
    ports:
      - "8080"
      - "8443"
    environment:
      - OPENHAB_HTTP_PORT=8080
      - OPENHAB_HTTPS_PORT=8443